apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: myapp
      version: green

  template:
    metadata:
      labels:
        app: myapp
        version: green

    spec:
      containers:
        - name: green-app
          image: bluegreen-app:1
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: GREEN
            - name: APP_VERSION
              value: "2.0"